### ISSUE TITLE
`MatrixView`: use border for transient selections

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#1020]
It should be relatively easy to implement a border for the “outer edge” of a selected region. This would probably work better than the current font weight/colour style for transient selections and would accord more with the `distill.pub` handcrafted example.

### Roadmap

- [x] Set independent x- and y-coordinates for each cell – 9ab93d2
- [x] Lift `translate` and other common attributes in each row to an outer container in `svg` – d946022
- [x] Add 4 SVG `line` elements for each cell with same visual attributes as the `rect` border – d946022
- [x] Move the highlight borders (SVG `line`s) into a separate layer and make them non-overlapping -- 620dac0
- [x] Add MatrixHelpers in PureScript – 279c12c
- [x] Implement a function that computes which sides (SVG `line`s) of the cells are to be highlighted as transient selection changes -- d40e9ba
- [x] Integrate that function to MatrixHelpers and the JavaScript side -- d40e9ba
- [x] Distinguish interior and exterior sides of the border using shadows -- 29a3c6a

**Comment by rolyp** [comment]
Hi @hafniz. Added a mock-up of the border idea to the issue description above. Once that's in place we might want to rethink the blue font colour/weight too. Also probably worth pointing out that this border is for transient selections only.

Just to reiterate the proposed methodology from yesterday: my suggestion is to leave the actual changes to the border to a later step, and first make the generalisation from rendering a cell as a single SVG `rect` to 4 SVG `line` objects (styles to look just the `rect` is currently styled). This should provide a relatively risk-free refactoring path which preserves existing behaviour whilst building in the generality we need to implement the feature. At that point we would come back to `MatrixViewHelpers`.

I'm tied up from 11-12 today but we can chat either 12:15 or so or later this afternoon to suit you.

**Comment by rolyp** [comment]
Hi @hafniz. It’s up to you but I find it useful to document the various subtasks as they arise as part of the GitHub issue and then check them off, e.g.:
- [ ] Add 4 SVG `line` elements for each cell with same visual attributes as `rect` border

It’s always useful to be working to a plan!

**Comment by hafniz** [comment]
### Roadmap

- [x] Set independent x- and y-coordinates for each cell -- 9ab93d2
- [ ] Lift the `translate` attribute in each row to an outer container in `svg`
- [ ] Add 4 SVG `line` elements for each cell with same visual attributes as the `rect` border
- [x] Add MatrixHelpers in PureScript -- 279c12c
- [ ] Implement a function that computes which sides (SVG `line`s) of the cells are to be highlighted as transient selection changes
- [ ] Integrate that function to MatrixHelpers and the JavaScript side

**Comment by hafniz** [comment]
We are currently drawing cells row by row, from top to bottom, declaring the `rect`, the text and the 4 borders for each cell before moving to the next. However, SVG elements declared later in the code will be rendered on top of those declared earlier. See the image below, where the highlighted south border of the top cell is covered by the inactive north border of the bottom cell.

![image](https://github.com/user-attachments/assets/99d49197-7096-4e9e-a877-94211cea9218)

Since there is no attribute equivalent to `z-index` that allows direct control of the order of overlapping in SVG, we might need to draw all the highlight borders (visibility all default to hidden and will be updated as the mouse moves) only after the whole matrix/all the cells has been drawn.

Essentially this will separate MatrixView into two layers, the bottom layer controlling the cell background and text style only, and a layer on top controlling the highlight borders:

```html
<svg>
<g> <!-- lower layer for the matrix -->
    <g> <!-- first row -->
        <rect ... /> <text ... />
        <rect ... /> <text ... />
    </g>
    <g> <!-- second row and so on --> </g>
</g>

<g> <!-- upper layer for the borders -->
    <g> <!-- first row -->
        <g> <line ... /> <line ... /> <line ... /> <line ... /> </g> <!-- 4 borders for the first cell -->
        <g> <line ... /> <line ... /> <line ... /> <line ... /> </g> <!-- 4 borders for the second cell -->
    </g>
    <g> <!-- second row and so on --> </g>
</g>
</svg>
```

And then in `setSelState` we just append another block that looks like `rootElement.selectAll('.matrix-cell-border').each(function (cell) { ... })` to the existing implementation.

Otherwise we can also remove the `rect` borders and draw all (highlighted and inactive) borders together, but that will involve reordering the code every time the mouse moves, such that the inactive borders are always declared before the highlight borders. Given the existing code structure I think this is much harder to achieve.

**Comment by rolyp** [comment]
@hafniz - right! That makes a lot of sense (and nicely summarised). I suppose we could also consider the “single shared border” idea I mentioned yesterday, but I feel like to make that idea work well we’d want the borders in their own layer anyway (because the relationship between cells and their constitutive lines is no longer 1-to-1).

So your proposal of splitting into two layers sounds like a good way forward and might make it easier to move to a shared border design in the future. For now I guess there is an implicit symmetry that requires (for “interior” borders of a transiently selected region) the visual attributes of the S border of cell (i, j) to be equal to the visual attributes of the N border of cell (i, j+1), which is probably [observationally] equivalent to saying the two cells share an interior.

**Comment by hafniz** [comment]
> requires the visual attributes of the S border of cell (i, j) to be equal to the visual attributes of the N border of cell (i, j+1)

I think the point of having overlapping borders instead of shared borders is that they behave like an OR gate - setting the visibility of either of the two borders at the same physical location gives the same visual effect. This allows us to think in terms of matrix cells only instead of manipulating the line segments direct: say if there is some shape whose border we would like to highlight, and that the (i, j) cell is one of the lowest cells of that shape, then we can just set the S border of the (i, j) cell without the need to consider the (i, j+1) cell. 

(I imagine the data structure that the code returns would look like a 2D array of {bool, bool, bool, bool}, specifying if that cell has no immediate {N, E, S, W} neighbours and thus its {N, E, S, W} borders need to be highlighted.)

Of course it is also not hard to translate from the above representation to a 2D array of booleans of dimension (height of matrix + 1) * (width of matrix + 1) specifying the visibility of each line segment if we were to use single shared borders. I think which approach is more intuitive/convenient will depend on the algorithm we use to determine the borders to highlight.

**Comment by rolyp** [comment]
Gotcha, I’d forgotten we were talking about setting `visible` for the transient highlighting and that the “interior” borders are provided by the underlying `rect`.

**Comment by rolyp** [comment]
Really good work @hafniz. These are all minor stylistic suggestions:

`hBorderShadowDirection` and `vBorderShadowDirection` would be slightly clearer without the initial `case`, given that you use guards on `i` anyway (`otherwise` in PureScript is just a synonym for `true` and so can be used as a guard):

```purescript
hBorderShadowDirection :: IntMatrix -> MatrixBorderCoordinate -> ShadowDirection
hBorderShadowDirection { cells, i: matrixH } { i, j }
   | i == 0 = 
      if isCellTransient cells { i, j: j - 1 } then South else None
   | i == matrixH = 
      if isCellTransient cells { i: i - 1, j: j - 1 } then North else None
   | otherwise =
      if isCellTransient cells { i, j: j - 1 } && not isCellTransient cells { i: i - 1, j: j - 1 } then South
      else if (not isCellTransient cells { i, j: j - 1 }) && isCellTransient cells { i: i - 1, j: j - 1 } then North
      else None
```

`hBorderStyles` and `vBorderStyles` would be slightly more idiomatic as:
```purescript
hBorderStyles :: IntMatrix -> MatrixBorderCoordinate -> String
hBorderStyles m = matrixBorderStyles <<< hBorderShadowDirection m
```

I feel like `matrixH` and `matrixW` might be clearer just as `height` and `width`.

`(arr2d ! i) ! j` can be written just as `arr2d ! i ! j`.

`(not isCellTransient cells { i, j: j - 1 })` can be written without the parentheses too (function application is always higher precedence than any operator).

Stylistically we’ve used single-quote JavaScript strings for strings that act as “tokens” or “symbols” (e.g. the names of CSS attributes like `style`). I don’t think we’ve used it entirely consistently, but for now it might best to stick to that convention.
