### ISSUE TITLE
IPCC AR6: Paragraphs B.1.1 and B.1.2

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/fluid#1188]

**Comment by rolyp** [comment]
I’ve been playing around with this example for my poster on Monday, and (as per my Slack comment this morning), I think we probably need to mock up a “plausible” underlying dataset and use that to illustrate what we want to do. My vague understanding so far is that we want to (a) imagine that there are a bunch of “samples” of predicted temperatures drawn from a particular scenario/time period. (These will themselves be the output of ensembles I guess but we can ignore that dimension of aggregation.)

So, mocked up in Excel, something like:

<img src="https://github.com/user-attachments/assets/c6ced53e-5ca3-4286-a9ff-b696b0b0fc39" width="200">
<br>

Then the idea would be to bin that data into temperature **ranges** (e.g. 0.1°C intervals), so that we can count how many samples fall into a particular bin, and use that proportion of the total number of samples as the probability. (Because it doesn’t really makes sense, at least intuitively to me, to ask what the probability of a given model producing a single specific real number is – I think the probability of a “point” is in some sense zero, so we need to consider intervals instead.)

That leads to some kind of histogram (again, just mocked up, but we would derive this from the pretend dataset above):

<img src="https://github.com/user-attachments/assets/8ea3080e-995b-4e60-a471-ea7c1cdb6668" width="300">

Then we can think of the **very likely** range as mapping to the central 90% of this histogram, which is a bit more tractable. And we could think of the histogram as a “visual output”, i.e. the binning is both “visual” and “analytic”, in the sense that we can (perhaps) take the data in the histogram and directly work with that for subsequent analyses. And that would give us reason to support inputs that are also outputs, and to show the compositional/nested provenance, because the user could also select a bar in the histogram and see what actual samples contributed to that bin.

**Comment by JosephBond** [comment]
You are correct that with a continuous quantity such as temperature, the probability of a specific value is 0 (the analogue of the sum in discrete probability is an integral, and evaluating an integral at a single point always gives 0).
I spent a good chunk of time trying to get an understanding of the datasets used in the SPM / IPCC report proper, and come to the conclusion that any more effort expended in that direction will be wasted right now, I agree we should just mock up some facsimile of the underlying distributions like you've done, and work from there. 

In your example did you generate the data or did you just pick some numbers by hand? In order to be a "plausible" we probably want a good number of fake datapoints from which to compute our percentiles

**Comment by rolyp** [comment]
I tried to generate the data using Chat GPT, but it couldn’t generate anything that summed to zero and had the required distribution w.r.t. the percentiles.

Could you use this issue to record your understanding of the datasets used in the IPCC report proper? it would be good to know what the issues are (and where the datasets are) so that we can come back to it, even if we end up creating our own simplified views of the “real” datasets.

**Comment by rolyp** [comment]
Thanks, that’s useful.

**Comment by JosephBond** [comment]
Original data sources for CMIP6 can be found [here](https://catalogue.ceda.ac.uk/uuid/b96ce180077f4810abc4eef0e48901d9/), but again I think sifting through all of these is probably a red herring

**Comment by JosephBond** [comment]
# Figure SPM 4B:
![image](https://github.com/user-attachments/assets/156717a5-5702-41e4-95c6-6f8fe1db29f7)

Want our multiple barchart example to reflect this example
### Code Improvements
- [x] Change title on html page
- [ ] In order to shift to using the exact data from the IPCC report, we need to complete the negative-bars task
### Missing Features
- [ ] Negative bars - explorable-viz/fluid#1184
- [ ] Finer-grained selections on bar-charts 
  - [ ] Need to be able to select components other than `z` of a bar-segment, ie the `y` and `x` values (or their fields) - explorable-viz/fluid#168
- [ ] Whiskers at the tip of bars for confidence intervals -  explorable-viz/fluid#1185
- [ ] explorable-viz/fluid#270
- [ ] Present as facet plot: one view containing all charts, then an individual view for each subchart - explorable-viz/fluid#1183

Related: explorable-viz/fluid#1161
@rolyp comment:
We have some really nice examples from the IPCC AR6 Summary for Policy Makers of text that refers in non-trivial ways to visualisations, e.g. referring common substructure shared by a bunch of bar charts. Mock this up in Fluid (not necessarily using real data, at least initially) to start to tease out some of the issues that come up.

A key idea here is that **selecting text** computed from a subcomponent of a visualisation induces a **selection on the subcomponent**. This is a new use case for us, as we haven't yet treated a visualisation as an input to a later stage in the computation. There may be some implied changes to the (currently rather simplistic) `Fig` setup.

See also:
- explorable-viz/fluid#270

**Comment by JosephBond** [comment]
# Table SPM 1:
![image](https://github.com/user-attachments/assets/5b34184c-93ca-4b82-b2cc-f67069c3f66f)
